[workspace]
members = [
    "crates/stwo",
    "crates/air-utils",
    "crates/air-utils-derive",
    "crates/constraint-framework",
    "crates/examples",
    "crates/std-shims",
]
exclude = ["ensure-verifier-no_std"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"

[workspace.dependencies]
itertools = { version = "0.12", default-features = false, features = [
    "use_alloc",
] }
blake2 = { version = "0.10.6", default-features = false }
blake3 = { version = "1.5.0", default-features = false }
educe = "0.5.0"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
num-traits = { version = "0.2.19", default-features = false }
thiserror = { version = "2.0.12", default-features = false }
bytemuck = { version = "1.14.3", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
rayon = { version = "1.10.0", optional = false }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
hashbrown = ">=0.15.2"
std-shims = { path = "crates/std-shims", default-features = false }

[profile.bench]
codegen-units = 1
lto = true
